[build]
builder = "NIXPACKS"
buildCommand = "pip install -r requirements.txt"

[deploy]
startCommand = "uvicorn api.main:app --host 0.0.0.0 --port $PORT"
healthcheckPath = "/health"
healthcheckTimeout = 30
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10

[variables]
PYTHON_VERSION = "3.10"
ENVIRONMENT = "production"

# Performance optimizations for Railway
[build.nixpacks]
providers = ["python"]
pythonVersion = "3.10"

[deploy.scaling]
minInstances = 1
maxInstances = 10

# Cron service for model training (separate service)
[[services]]
name = "model-trainer"
type = "cron"
schedule = "0 0 * * 0"  # Weekly on Sunday
buildCommand = "pip install -r requirements.txt"
startCommand = "python api/jobs/weekly_retrain.py"

[[services]]
name = "daily-updater"
type = "cron"
schedule = "0 3 * * *"  # Daily at 3 AM
buildCommand = "pip install -r requirements.txt"
startCommand = "python api/jobs/daily_update.py"