# railway.toml - Railway's Python template configuration

[build]
builder = "NIXPACKS"
buildCommand = "python -m venv /opt/venv && /opt/venv/bin/pip install -r requirements.txt"

[deploy]
startCommand = "/opt/venv/bin/python -m uvicorn api.main:app --host 0.0.0.0 --port $PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 30

[nixpacks]
python_version = "3.10"