# railway.toml - Corrected to ensure Python is installed first

[build]
builder = "NIXPACKS"
# Remove buildCommand - let Nixpacks handle the build process

[deploy]
startCommand = "uvicorn api.main:app --host 0.0.0.0 --port $PORT"
restartPolicyType = "ON_FAILURE"
restartPolicyMaxRetries = 10
healthcheckPath = "/health"
healthcheckTimeout = 30

[nixpacks]
python_version = "3.10"